parameters: # user-configurable parameters
  - name: skip_assembly_signing
    displayName: Skip Assembly Signing
    type: boolean
    default: false

pr:
  branches:
    include:
    - main
    - dev
  paths:
    exclude: # don't trigger builds for file changes matching these paths
    - src/WebJobs.Extensions.CosmosDB/*

trigger:
  branches:
    include:
    - main
    - dev
  tags:
    exclude:
      - cosmos-v*
  paths:
    exclude: # don't trigger builds for file changes matching these paths
    - test/WebJobs.Extensions.CosmosDB.Tests/*

extends: 
  template: build/pipelines/templates/ci.yml
  parameters: # template parameters
    skip_assembly_signing: ${{ parameters.skip_assembly_signing }}
    target_projects:
      - WebJobs.Extensions
      - WebJobs.Extensions.Http
      - WebJobs.Extensions.SendGrid
      - WebJobs.Extensions.Timers.Storage
      - WebJobs.Extensions.Twilio
      # WebJobs.Extensions.CosmosDB is run by a separate pipeline defined in its src/ folder
    target_tests:
      - WebJobs.Extensions.Tests
      - WebJobs.Extensions.Http.Tests
      - WebJobs.Extensions.MobileApps.Tests
      - WebJobs.Extensions.SendGrid.Tests
      - WebJobs.Extensions.Twilio.Tests