<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <NoWarn>$(NoWarn);8002</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SrcRoot)WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj" />
    <ProjectReference Include="../WebJobs.Extensions.Tests.Common/WebJobs.Extensions.Tests.Common.csproj" />
  </ItemGroup>

</Project>