<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SrcRoot)WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj" />
    <ProjectReference Include="../WebJobs.Extensions.Tests.Common/WebJobs.Extensions.Tests.Common.csproj" />
  </ItemGroup>

</Project>