<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SrcRoot)WebJobs.Extensions.Timers.Storage/WebJobs.Extensions.Timers.Storage.csproj" />
    <ProjectReference Include="../WebJobs.Extensions.Tests.Common/WebJobs.Extensions.Tests.Common.csproj" />
  </ItemGroup>

</Project>