parameters:
- name: projects
  type: string
- name: folder
  type: string
- name: public
  type: boolean
  default: false

stages:
- stage: Build
  jobs:
  - template: /eng/ci/templates/jobs/build.yml@self
    parameters:
      sign: true
      projects: ${{ parameters.projects}}

- stage: Release
  dependsOn: Build
  jobs:
  - template: /ci/release-nuget-package.yml@eng
    parameters:
      isProduction: true
      approvers: '[internal]\Azure Functions Core'
      artifact: drop_packages
      stagingFeed: public/pre-release
      packages: |
        **/*.nupkg
        !**/*.symbols.nupkg
      ${{ if eq(parameters.public, true) }}:
        partnerDrop:
          serviceConnection: azure-sdk-partner-drops
          targetFolder: azure-functions/dotnet/${{ parameters.folder }}/$(Build.BuildNumber)
