<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- We use a package reference to avoid building this in CI. -->
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="5.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SrcRoot)WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj" />
    <ProjectReference Include="../WebJobs.Extensions.Tests.Common/WebJobs.Extensions.Tests.Common.csproj" />
  </ItemGroup>

</Project>