trigger:
  branches:
    include:
    # Below branches are examples for Azure/azure-functions-host. Replace with appropriate branches for your repository.
    # Keep this set limited as appropriate (don't mirror individual user branches).
    - dev

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng
