parameters:
- name: public
  displayName: Publish to nuget.org?
  type: boolean
  default: false

# Release has no triggers outside of pipeline
trigger: none
pr: none

extends:
  template: /eng/ci/templates/pipelines/release.yml@self
  parameters:
    public: ${{ parameters.public }}
    folder: azure-webjobs-extensions
    projects: |
      $(Build.SourcesDirectory)/src/WebJobs.Extensions/WebJobs.Extensions.csproj
      $(Build.SourcesDirectory)/test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
