parameters:
- name: sign
  type: boolean
  default: false
- name: extra_args
  type: string
  default: ''
- name: projects
  type: string

jobs:
- job: build
  displayName: Build

  variables:
  - template: /eng/ci/templates/variables/build.yml@self
  - name: pack_dir
    value: $(Build.ArtifactStagingDirectory)/pkg

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish logs
      path: $(pack_dir)
      artifact: drop_packages

  steps:
    - template: /eng/ci/templates/steps/install-dotnet.yml@self

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: custom
        custom: restore
        projects: ${{ parameters.projects }}
        arguments: -v m

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: ${{ parameters.projects }}
        arguments: -c $(configuration) -v m --no-restore ${{ parameters.extra_args }}

    - template: /eng/ci/templates/steps/start-emulators.yml@self

    - task: DotNetCoreCLI@2
      displayName: Unit tests
      inputs:
        command: test
        arguments: -c $(configuration) --no-build
        projects: ${{ parameters.projects }}
      env:
        AzureWebJobsStorage: $(Storage)
        AzureWebJobsDashboard: $(Storage)
        AzureWebJobsCosmosDBConnectionString: $(CosmosDB)
        ConnectionStrings__CosmosDB: $(CosmosDB)

    - ${{ if eq(parameters.sign, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign assemblies
          minimatch: true
          signType: dll-strong-name
          folderPath: out/bin/src
          pattern: |
            **/Microsoft.Azure.WebJobs.Extensions*.dll

    - task: DotNetCoreCLI@2
      displayName: Pack
      inputs:
        command: custom
        custom: pack
        arguments: -c $(configuration) -v m -o $(pack_dir) --no-build
        projects: ${{ parameters.projects }}

    - ${{ if eq(parameters.sign, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign nuget packages
          signType: nuget
          folderPath: $(pack_dir)
          pattern: Microsoft.Azure.WebJobs.Extensions*.nupkg

      - task: DeleteFiles@1
        displayName: Delete CodeSignSummary files
        inputs:
          contents: $(pack_dir)/CodeSignSummary-*.md
