parameters:
- name: sign
  type: boolean
  default: false
- name: project
  type: string

jobs:
- job: build
  displayName: Build

  variables:
  - name: log_dir
    value: $(Build.ArtifactStagingDirectory)/log
  - name: pack_dir
    value: $(Build.ArtifactStagingDirectory)/pkg
  - name: buildNumber
    value: $[ counter('constant', 12000) ]
  - name: sign
    value: ${{ parameters.sign }}

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish logs
      path: $(pack_dir)
      artifact: drop_packages

  steps:
    - template: /eng/ci/templates/steps/install-dotnet.yml@self

    # If sign=false, verify this is not an "sign" branch
    - ${{ if ne(parameters.sign, true) }}:
      - pwsh: |
          $source = "$(Build.SourceBranch)"
          if ($source -like "refs/tags/*-v*" || $source -like "refs/tags/v*" || $source -like "refs/heads/release/*")
          {
            Write-Host "##vso[task.logissue type=error]Branch/tag $source must have 'sign' set to 'true'."
            exit 1
          }
        displayName: Verify not sign branch

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: custom
        custom: restore
        projects: ${{ parameters.project }}
        arguments: -v m

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: ${{ parameters.project }}
        arguments: -c $(configuration) -v m --no-restore -p:CommitHash=$(Build.SourceVersion)

    - template: /eng/ci/templates/steps/start-emulators.yml@self

    - task: DotNetCoreCLI@2
      displayName: Unit tests
      inputs:
        command: test
        arguments: -c $(configuration) --no-build
        projects: ${{ parameters.project }}
      env:
        AzureWebJobsStorage: $(Storage)
        AzureWebJobsDashboard: $(Storage)
        AzureWebJobsCosmosDBConnectionString: $(CosmosDB)
        ConnectionStrings__CosmosDB: $(CosmosDB)

    - ${{ if eq(parameters.sign, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign assemblies
          folderPath: src
          pattern: Microsoft.Azure.WebJobs.Extensions*.dll
          signType: dll-strong-name

    - task: DotNetCoreCLI@2
      displayName: Pack
      inputs:
        command: custom
        custom: pack
        arguments: -c $(configuration) -v m -o $(pack_dir) --no-build
        projects: ${{ parameters.project }}

    - ${{ if eq(parameters.sign, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign nuget packages
          folderPath: $(pack_dir)
          pattern: Microsoft.Azure.WebJobs.Extensions*.nupkg
          signType: nuget

      - task: DeleteFiles@1
        displayName: Delete CodeSignSummary files
        inputs:
          contents: $(pack_dir)/CodeSignSummary-*.md
